https://www.kaggle.com/datasets/pralabhpoudel/world-energy-consumption

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_rows", 200)

In [24]:
WEC_Dataframe = pd.read_csv("World Energy Consumption.csv")

WEC_Dataframe.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [25]:
WEC_Dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22012 entries, 0 to 22011
Columns: 129 entries, country to wind_share_energy
dtypes: float64(126), int64(1), object(2)
memory usage: 21.7+ MB

In [26]:
WEC_Dataframe.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,22012.000000,1.812300e+04,1.111300e+04,1747.000000,2687.000000,2302.000000,2767.000000,5275.000000,5527.000000,5492.000000,...,6849.000000,4035.000000,2413.000000,4639.000000,4744.000000,7065.000000,7996.000000,4065.000000,6886.000000,4101.000000
mean,1974.213247,1.053096e+08,3.585114e+11,46.091694,2.719074,133.558459,38.068209,64.716800,10.966685,1.954035,...,0.622750,0.210395,267.541206,7.314174,53.422938,62.811828,17.561153,232.108949,1.404910,0.651413
std,35.058653,4.640460e+08,2.411179e+12,274.616745,10.057018,264.707851,111.623148,201.043915,47.953561,5.274155,...,2.066186,0.643304,5940.944120,37.327922,273.255306,252.734217,101.693172,733.841324,4.489043,1.893820
min,1900.000000,1.833000e+03,1.642060e+08,-100.000000,-50.843000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-100.000000,-51.208000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1946.000000,1.712404e+06,1.365898e+10,-0.616500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.029000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1984.000000,6.991543e+06,4.167411e+10,8.179000,0.000000,15.482000,0.673000,0.146000,0.010000,0.062000,...,0.000000,0.000000,20.000000,0.000000,0.005000,0.000000,0.000000,0.051000,0.000000,0.003000
75%,2003.000000,2.557688e+07,1.744295e+11,26.508500,0.861500,165.266750,13.629500,34.289000,0.690000,1.577500,...,0.095000,0.018500,47.971000,0.315000,2.357750,2.101000,0.140000,45.523000,0.372000,0.268000
max,2022.000000,7.975105e+09,1.136302e+14,5659.328000,141.131000,2588.512000,1199.207000,2514.102000,677.570000,71.429000,...,40.000000,7.586000,242384.844000,665.413000,5487.600000,3219.852000,2139.230000,8422.012000,56.840000,26.157000

In [27]:
cols = WEC_Dataframe.columns.tolist()

for c in cols:
    print(c)

country
year
iso_code
population
gdp
biofuel_cons_change_pct
biofuel_cons_change_twh
biofuel_cons_per_capita
biofuel_consumption
biofuel_elec_per_capita
biofuel_electricity
biofuel_share_elec
biofuel_share_energy
carbon_intensity_elec
coal_cons_change_pct
coal_cons_change_twh
coal_cons_per_capita
coal_consumption
coal_elec_per_capita
coal_electricity
coal_prod_change_pct
coal_prod_change_twh
coal_prod_per_capita
coal_production
coal_share_elec
coal_share_energy
electricity_demand
electricity_generation
electricity_share_energy
energy_cons_change_pct
energy_cons_change_twh
energy_per_capita
energy_per_gdp
fossil_cons_change_pct
fossil_cons_change_twh
fossil_elec_per_capita
fossil_electricity
fossil_energy_per_capita
fossil_fuel_consumption
fossil_share_elec
fossil_share_energy
gas_cons_change_pct
gas_cons_change_twh
gas_consumption
gas_elec_per_capita
gas_electricity
gas_energy_per_capita
gas_prod_change_pct
gas_prod_change_twh
gas_prod_per_capita
gas_production
gas_share_elec
gas_share_energy
greenhouse_gas_emissions
hydro_cons_change_pct
hydro_cons_change_twh
hydro_consumption
hydro_elec_per_capita
hydro_electricity
hydro_energy_per_capita
hydro_share_elec
hydro_share_energy
low_carbon_cons_change_pct
low_carbon_cons_change_twh
low_carbon_consumption
low_carbon_elec_per_capita
low_carbon_electricity
low_carbon_energy_per_capita
low_carbon_share_elec
low_carbon_share_energy
net_elec_imports
net_elec_imports_share_demand
nuclear_cons_change_pct
nuclear_cons_change_twh
nuclear_consumption
nuclear_elec_per_capita
nuclear_electricity
nuclear_energy_per_capita
nuclear_share_elec
nuclear_share_energy
oil_cons_change_pct
oil_cons_change_twh
oil_consumption
oil_elec_per_capita
oil_electricity
oil_energy_per_capita
oil_prod_change_pct
oil_prod_change_twh
oil_prod_per_capita
oil_production
oil_share_elec
oil_share_energy
other_renewable_consumption
other_renewable_electricity
other_renewable_exc_biofuel_electricity
other_renewables_cons_change_pct
other_renewables_cons_change_twh
other_renewables_elec_per_capita
other_renewables_elec_per_capita_exc_biofuel
other_renewables_energy_per_capita
other_renewables_share_elec
other_renewables_share_elec_exc_biofuel
other_renewables_share_energy
per_capita_electricity
primary_energy_consumption
renewables_cons_change_pct
renewables_cons_change_twh
renewables_consumption
renewables_elec_per_capita
renewables_electricity
renewables_energy_per_capita
renewables_share_elec
renewables_share_energy
solar_cons_change_pct
solar_cons_change_twh
solar_consumption
solar_elec_per_capita
solar_electricity
solar_energy_per_capita
solar_share_elec
solar_share_energy
wind_cons_change_pct
wind_cons_change_twh
wind_consumption
wind_elec_per_capita
wind_electricity
wind_energy_per_capita
wind_share_elec
wind_share_energy

In [28]:
column_code = pd.read_csv("owid-energy-codebook.csv")

In [29]:
biofuel_data = WEC_Dataframe[[
    "country", 
    "year",
    "iso_code",
    "population", 
    "gdp", 
    "biofuel_cons_change_pct", 
    "biofuel_cons_change_twh", 
    "biofuel_cons_per_capita", 
    "biofuel_consumption", 
    "biofuel_elec_per_capita", 
    "biofuel_electricity", 
    "biofuel_share_elec", 
    "biofuel_share_energy"
]].copy()

biofuel_data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.60,1.519,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.02,1.516,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.06,1.433,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.69,1.496,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.57,1.561,NaN

In [30]:
biofuel_data = biofuel_data.rename(columns = {
    "biofuel_cons_change_pct": "biofuel-cons_change_pct_%", 
    "biofuel_cons_per_capita": "biofuel_cons_per_capita_kWh",
    "biofuel_consumption": "biofuel_consumption_TWh",
    "biofuel_elec_per_capita": "biofuel_elec_per_capita_kWh",
    "biofuel_electricity": "biofuel_electricity_TWh",
    "biofuel_share_elec": "biofuel_share_elec_%",
    "biofuel_share_energy": "biofuel_share_energy_%"
})

biofuel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22012 entries, 0 to 22011
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country                      22012 non-null  object
 1   year                         22012 non-null  int64
 2   iso_code                     16512 non-null  object
 3   population                   18123 non-null  float64
 4   gdp                          11113 non-null  float64
 5   biofuel-cons_change_pct_%    1747 non-null   float64
 6   biofuel_cons_change_twh      2687 non-null   float64
 7   biofuel_cons_per_capita_kWh  2302 non-null   float64
 8   biofuel_consumption_TWh      2767 non-null   float64
 9   biofuel_elec_per_capita_kWh  5275 non-null   float64
 10  biofuel_electricity_TWh      5527 non-null   float64
 11  biofuel_share_elec_%         5492 non-null   float64
 12  biofuel_share_energy_%       2671 non-null   float64
dtypes: float64(10), int64(1), object(2)
memory usage: 2.2+ MB

In [31]:
coal_data = WEC_Dataframe[[
    "country", 
    "year",
    "iso_code",
    "population", 
    "gdp", 
    "coal_cons_change_pct", 
    "coal_cons_change_twh", 
    "coal_cons_per_capita", 
    "coal_consumption", 
    "coal_elec_per_capita", 
    "coal_electricity",
    "coal_prod_change_pct",
    "coal_prod_change_twh",
    "coal_prod_per_capita",
    "coal_production",
    "coal_share_elec", 
    "coal_share_energy",
]].copy()

coal_data.head()

,country,year,iso_code,population,gdp,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.03,NaN,NaN,NaN,NaN,19.268,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.02,NaN,NaN,NaN,NaN,20.147,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.16,NaN,NaN,NaN,NaN,20.614,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.51,NaN,NaN,NaN,NaN,22.031,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.62,NaN,NaN,NaN,NaN,23.017,NaN

In [32]:
coal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22012 entries, 0 to 22011
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               22012 non-null  object
 1   year                  22012 non-null  int64
 2   iso_code              16512 non-null  object
 3   population            18123 non-null  float64
 4   gdp                   11113 non-null  float64
 5   coal_cons_change_pct  5258 non-null   float64
 6   coal_cons_change_twh  5315 non-null   float64
 7   coal_cons_per_capita  4666 non-null   float64
 8   coal_consumption      5420 non-null   float64
 9   coal_elec_per_capita  5850 non-null   float64
 10  coal_electricity      6444 non-null   float64
 11  coal_prod_change_pct  9657 non-null   float64
 12  coal_prod_change_twh  16239 non-null  float64
 13  coal_prod_per_capita  14718 non-null  float64
 14  coal_production       16494 non-null  float64
 15  coal_share_elec       6409 non-null   float64
 16  coal_share_energy     4787 non-null   float64
dtypes: float64(14), int64(1), object(2)
memory usage: 2.9+ MB

In [33]:
coal_data = coal_data.rename(columns = {
    "coal_cons_change_pct": "coal-cons_change_pct_%", 
    "coal_cons_per_capita": "coal_cons_per_capita_kWh",
    "coal_consumption": "coal_consumption_TWh",
    "coal_elec_per_capita": "coal_elec_per_capita_kWh",
    "coal_electricity": "coal_electricity_TWh",
    "coal_prod_change_pct": "coal_prod_change_pct_%",
    "coal_prod_per_capita": "coal_prod_per_capita_kWh",
    "coal_production": "coal_production_TWh",
    "coal_share_elec": "coal_share_elec_%",
    "coal_share_energy": "coal_share_energy_%"
})

coal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22012 entries, 0 to 22011
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   country                   22012 non-null  object
 1   year                      22012 non-null  int64
 2   iso_code                  16512 non-null  object
 3   population                18123 non-null  float64
 4   gdp                       11113 non-null  float64
 5   coal-cons_change_pct_%    5258 non-null   float64
 6   coal_cons_change_twh      5315 non-null   float64
 7   coal_cons_per_capita_kWh  4666 non-null   float64
 8   coal_consumption_TWh      5420 non-null   float64
 9   coal_elec_per_capita_kWh  5850 non-null   float64
 10  coal_electricity_TWh      6444 non-null   float64
 11  coal_prod_change_pct_%    9657 non-null   float64
 12  coal_prod_change_twh      16239 non-null  float64
 13  coal_prod_per_capita_kWh  14718 non-null  float64
 14  coal_production_TWh       16494 non-null  float64
 15  coal_share_elec_%         6409 non-null   float64
 16  coal_share_energy_%       4787 non-null   float64
dtypes: float64(14), int64(1), object(2)
memory usage: 2.9+ MB